name = "spherical-vlds-system"
version = "0.1.0"
license = "license"
author = "Amir Saadeddine"
maintainer = "amir.saadeddine@ufv.br"
copyright = "Copyright 2025, Amir Saadeddine"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

